#pragma once

#include <unordered_map>

namespace nes {

enum class AddressMode {
	kACC,
	kABS,
	kABX,
	kABY,
	kIMM,
	kIMP,
	kIND,
	kINX,
	kINY,
	kREL,
	kZP,
	kZPX,
	kZPY,
};

constexpr int OpSizeByMode(AddressMode m) {
	switch (m) {
	    case AddressMode::kIMP:
	    case AddressMode::kACC:
			return 1;
	    case AddressMode::kIMM:
	    case AddressMode::kINX:
	    case AddressMode::kINY:
	    case AddressMode::kREL:
	    case AddressMode::kZP:
	    case AddressMode::kZPX:
	    case AddressMode::kZPY:
			return 2;
	    case AddressMode::kABS:
	    case AddressMode::kABX:
	    case AddressMode::kABY:
	    case AddressMode::kIND:
			return 3;
	}
}

enum class Instruction {
	kADC,
	kAND,
	kASL,
	kBCC,
	kBCS,
	kBEQ,
	kBIT,
	kBMI,
	kBNE,
	kBPL,
	kBRK,
	kBVC,
	kBVS,
	kCLC,
	kCLD,
	kCLI,
	kCLV,
	kCMP,
	kCPX,
	kCPY,
	kDEC,
	kDEX,
	kDEY,
	kEOR,
	kINC,
	kINX,
	kINY,
	kJMP,
	kJSR,
	kLDA,
	kLDX,
	kLDY,
	kLSR,
	kNOP,
	kORA,
	kPHA,
	kPHP,
	kPLA,
	kPLP,
	kROL,
	kROR,
	kRTI,
	kRTS,
	kSBC,
	kSEC,
	kSED,
	kSEI,
	kSTA,
	kSTX,
	kSTY,
	kTAX,
	kTAY,
	kTSX,
	kTXA,
	kTXS,
	kTYA,
	// "Illegal" Opcodes
	kLAX,
	kSAX,
	kUSBC,
	kDCP,
	kISC,
	kSLO,
	kRLA,
	kSRE,
	kRRA,
};

struct Operation {
	Instruction instr;
	AddressMode addrMode;
};

const std::unordered_map<int, Operation> kOpDecoder = {{
	{0x00, {Instruction::kBRK, AddressMode::kIMP}},
	{0x01, {Instruction::kORA, AddressMode::kINX}},
	{0x05, {Instruction::kORA, AddressMode::kZP}},
	{0x06, {Instruction::kASL, AddressMode::kZP}},
	{0x08, {Instruction::kPHP, AddressMode::kIMP}},
	{0x09, {Instruction::kORA, AddressMode::kIMM}},
	{0x0A, {Instruction::kASL, AddressMode::kACC}},
	{0x0D, {Instruction::kORA, AddressMode::kABS}},
	{0x0E, {Instruction::kASL, AddressMode::kABS}},
	{0x10, {Instruction::kBPL, AddressMode::kREL}},
	{0x11, {Instruction::kORA, AddressMode::kINY}},
	{0x15, {Instruction::kORA, AddressMode::kZPX}},
	{0x16, {Instruction::kASL, AddressMode::kZPX}},
	{0x18, {Instruction::kCLC, AddressMode::kIMP}},
	{0x19, {Instruction::kORA, AddressMode::kABY}},
	{0x1D, {Instruction::kORA, AddressMode::kABX}},
	{0x1E, {Instruction::kASL, AddressMode::kABX}},
	{0x20, {Instruction::kJSR, AddressMode::kABS}},
	{0x21, {Instruction::kAND, AddressMode::kINX}},
	{0x24, {Instruction::kBIT, AddressMode::kZP}},
	{0x25, {Instruction::kAND, AddressMode::kZP}},
	{0x26, {Instruction::kROL, AddressMode::kZP}},
	{0x28, {Instruction::kPLP, AddressMode::kIMP}},
	{0x29, {Instruction::kAND, AddressMode::kIMM}},
	{0x2A, {Instruction::kROL, AddressMode::kACC}},
	{0x2C, {Instruction::kBIT, AddressMode::kABS}},
	{0x2D, {Instruction::kAND, AddressMode::kABS}},
	{0x2E, {Instruction::kROL, AddressMode::kABS}},
	{0x30, {Instruction::kBMI, AddressMode::kREL}},
	{0x31, {Instruction::kAND, AddressMode::kINY}},
	{0x35, {Instruction::kAND, AddressMode::kZPX}},
	{0x36, {Instruction::kROL, AddressMode::kZPX}},
	{0x38, {Instruction::kSEC, AddressMode::kIMP}},
	{0x39, {Instruction::kAND, AddressMode::kABY}},
	{0x3D, {Instruction::kAND, AddressMode::kABX}},
	{0x3E, {Instruction::kROL, AddressMode::kABX}},
	{0x40, {Instruction::kRTI, AddressMode::kIMP}},
	{0x41, {Instruction::kEOR, AddressMode::kINX}},
	{0x45, {Instruction::kEOR, AddressMode::kZP}},
	{0x46, {Instruction::kLSR, AddressMode::kZP}},
	{0x48, {Instruction::kPHA, AddressMode::kIMP}},
	{0x49, {Instruction::kEOR, AddressMode::kIMM}},
	{0x4A, {Instruction::kLSR, AddressMode::kACC}},
	{0x4C, {Instruction::kJMP, AddressMode::kABS}},
	{0x4D, {Instruction::kEOR, AddressMode::kABS}},
	{0x4E, {Instruction::kLSR, AddressMode::kABS}},
	{0x50, {Instruction::kBVC, AddressMode::kREL}},
	{0x51, {Instruction::kEOR, AddressMode::kINY}},
	{0x55, {Instruction::kEOR, AddressMode::kZPX}},
	{0x56, {Instruction::kLSR, AddressMode::kZPX}},
	{0x58, {Instruction::kCLI, AddressMode::kIMP}},
	{0x59, {Instruction::kEOR, AddressMode::kABY}},
	{0x5D, {Instruction::kEOR, AddressMode::kABX}},
	{0x5E, {Instruction::kLSR, AddressMode::kABX}},
	{0x60, {Instruction::kRTS, AddressMode::kIMP}},
	{0x61, {Instruction::kADC, AddressMode::kINX}},
	{0x65, {Instruction::kADC, AddressMode::kZP}},
	{0x66, {Instruction::kROR, AddressMode::kZP}},
	{0x68, {Instruction::kPLA, AddressMode::kIMP}},
	{0x69, {Instruction::kADC, AddressMode::kIMM}},
	{0x6A, {Instruction::kROR, AddressMode::kACC}},
	{0x6C, {Instruction::kJMP, AddressMode::kIND}},
	{0x6D, {Instruction::kADC, AddressMode::kABS}},
	{0x6E, {Instruction::kROR, AddressMode::kABS}},
	{0x70, {Instruction::kBVS, AddressMode::kREL}},
	{0x71, {Instruction::kADC, AddressMode::kINY}},
	{0x75, {Instruction::kADC, AddressMode::kZPX}},
	{0x76, {Instruction::kROR, AddressMode::kZPX}},
	{0x78, {Instruction::kSEI, AddressMode::kIMP}},
	{0x79, {Instruction::kADC, AddressMode::kABY}},
	{0x7D, {Instruction::kADC, AddressMode::kABX}},
	{0x7E, {Instruction::kROR, AddressMode::kABX}},
	{0x81, {Instruction::kSTA, AddressMode::kINX}},
	{0x84, {Instruction::kSTY, AddressMode::kZP}},
	{0x85, {Instruction::kSTA, AddressMode::kZP}},
	{0x86, {Instruction::kSTX, AddressMode::kZP}},
	{0x88, {Instruction::kDEY, AddressMode::kIMP}},
	{0x8A, {Instruction::kTXA, AddressMode::kIMP}},
	{0x8C, {Instruction::kSTY, AddressMode::kABS}},
	{0x8D, {Instruction::kSTA, AddressMode::kABS}},
	{0x8E, {Instruction::kSTX, AddressMode::kABS}},
	{0x90, {Instruction::kBCC, AddressMode::kREL}},
	{0x91, {Instruction::kSTA, AddressMode::kINY}},
	{0x94, {Instruction::kSTY, AddressMode::kZPX}},
	{0x95, {Instruction::kSTA, AddressMode::kZPX}},
	{0x96, {Instruction::kSTX, AddressMode::kZPY}},
	{0x98, {Instruction::kTYA, AddressMode::kIMP}},
	{0x99, {Instruction::kSTA, AddressMode::kABY}},
	{0x9A, {Instruction::kTXS, AddressMode::kIMP}},
	{0x9D, {Instruction::kSTA, AddressMode::kABX}},
	{0xA0, {Instruction::kLDY, AddressMode::kIMM}},
	{0xA1, {Instruction::kLDA, AddressMode::kINX}},
	{0xA2, {Instruction::kLDX, AddressMode::kIMM}},
	{0xA4, {Instruction::kLDY, AddressMode::kZP}},
	{0xA5, {Instruction::kLDA, AddressMode::kZP}},
	{0xA6, {Instruction::kLDX, AddressMode::kZP}},
	{0xA8, {Instruction::kTAY, AddressMode::kIMP}},
	{0xA9, {Instruction::kLDA, AddressMode::kIMM}},
	{0xAA, {Instruction::kTAX, AddressMode::kIMP}},
	{0xAC, {Instruction::kLDY, AddressMode::kABS}},
	{0xAD, {Instruction::kLDA, AddressMode::kABS}},
	{0xAE, {Instruction::kLDX, AddressMode::kABS}},
	{0xB0, {Instruction::kBCS, AddressMode::kREL}},
	{0xB1, {Instruction::kLDA, AddressMode::kINY}},
	{0xB4, {Instruction::kLDY, AddressMode::kZPX}},
	{0xB5, {Instruction::kLDA, AddressMode::kZPX}},
	{0xB6, {Instruction::kLDX, AddressMode::kZPY}},
	{0xB8, {Instruction::kCLV, AddressMode::kIMP}},
	{0xB9, {Instruction::kLDA, AddressMode::kABY}},
	{0xBA, {Instruction::kTSX, AddressMode::kIMP}},
	{0xBC, {Instruction::kLDY, AddressMode::kABX}},
	{0xBD, {Instruction::kLDA, AddressMode::kABX}},
	{0xBE, {Instruction::kLDX, AddressMode::kABY}},
	{0xC0, {Instruction::kCPY, AddressMode::kIMM}},
	{0xC1, {Instruction::kCMP, AddressMode::kINX}},
	{0xC4, {Instruction::kCPY, AddressMode::kZP}},
	{0xC5, {Instruction::kCMP, AddressMode::kZP}},
	{0xC6, {Instruction::kDEC, AddressMode::kZP}},
	{0xC8, {Instruction::kINY, AddressMode::kIMP}},
	{0xC9, {Instruction::kCMP, AddressMode::kIMM}},
	{0xCA, {Instruction::kDEX, AddressMode::kIMP}},
	{0xCC, {Instruction::kCPY, AddressMode::kABS}},
	{0xCD, {Instruction::kCMP, AddressMode::kABS}},
	{0xCE, {Instruction::kDEC, AddressMode::kABS}},
	{0xD0, {Instruction::kBNE, AddressMode::kREL}},
	{0xD1, {Instruction::kCMP, AddressMode::kINY}},
	{0xD5, {Instruction::kCMP, AddressMode::kZPX}},
	{0xD6, {Instruction::kDEC, AddressMode::kZPX}},
	{0xD8, {Instruction::kCLD, AddressMode::kIMP}},
	{0xD9, {Instruction::kCMP, AddressMode::kABY}},
	{0xDD, {Instruction::kCMP, AddressMode::kABX}},
	{0xDE, {Instruction::kDEC, AddressMode::kABX}},
	{0xE0, {Instruction::kCPX, AddressMode::kIMM}},
	{0xE1, {Instruction::kSBC, AddressMode::kINX}},
	{0xE4, {Instruction::kCPX, AddressMode::kZP}},
	{0xE5, {Instruction::kSBC, AddressMode::kZP}},
	{0xE6, {Instruction::kINC, AddressMode::kZP}},
	{0xE8, {Instruction::kINX, AddressMode::kIMP}},
	{0xE9, {Instruction::kSBC, AddressMode::kIMM}},
	{0xEA, {Instruction::kNOP, AddressMode::kIMP}},
	{0xEC, {Instruction::kCPX, AddressMode::kABS}},
	{0xED, {Instruction::kSBC, AddressMode::kABS}},
	{0xEE, {Instruction::kINC, AddressMode::kABS}},
	{0xF0, {Instruction::kBEQ, AddressMode::kREL}},
	{0xF1, {Instruction::kSBC, AddressMode::kINY}},
	{0xF5, {Instruction::kSBC, AddressMode::kZPX}},
	{0xF6, {Instruction::kINC, AddressMode::kZPX}},
	{0xF8, {Instruction::kSED, AddressMode::kIMP}},
	{0xF9, {Instruction::kSBC, AddressMode::kABY}},
	{0xFD, {Instruction::kSBC, AddressMode::kABX}},
	{0xFE, {Instruction::kINC, AddressMode::kABX}},
// "Illegal" Opcodes and Undocumented Instructions
	{0xA7, {Instruction::kLAX, AddressMode::kZP}},
	{0xB7, {Instruction::kLAX, AddressMode::kZPY}},
	{0xAF, {Instruction::kLAX, AddressMode::kABS}},
	{0xBF, {Instruction::kLAX, AddressMode::kABY}},
	{0xA3, {Instruction::kLAX, AddressMode::kINX}},
	{0xB3, {Instruction::kLAX, AddressMode::kINY}},
	{0x1A, {Instruction::kNOP, AddressMode::kIMP}},
	{0x3A, {Instruction::kNOP, AddressMode::kIMP}},
	{0x5A, {Instruction::kNOP, AddressMode::kIMP}},
	{0x7A, {Instruction::kNOP, AddressMode::kIMP}},
	{0xDA, {Instruction::kNOP, AddressMode::kIMP}},
	{0xFA, {Instruction::kNOP, AddressMode::kIMP}},
	{0x80, {Instruction::kNOP, AddressMode::kIMM}},
	{0x82, {Instruction::kNOP, AddressMode::kIMM}},
	{0x89, {Instruction::kNOP, AddressMode::kIMM}},
	{0xC2, {Instruction::kNOP, AddressMode::kIMM}},
	{0xE2, {Instruction::kNOP, AddressMode::kIMM}},
	{0x04, {Instruction::kNOP, AddressMode::kZP}},
	{0x44, {Instruction::kNOP, AddressMode::kZP}},
	{0x64, {Instruction::kNOP, AddressMode::kZP}},
	{0x14, {Instruction::kNOP, AddressMode::kZPX}},
	{0x34, {Instruction::kNOP, AddressMode::kZPX}},
	{0x54, {Instruction::kNOP, AddressMode::kZPX}},
	{0x74, {Instruction::kNOP, AddressMode::kZPX}},
	{0xD4, {Instruction::kNOP, AddressMode::kZPX}},
	{0xF4, {Instruction::kNOP, AddressMode::kZPX}},
	{0x0C, {Instruction::kNOP, AddressMode::kABS}},
	{0x1C, {Instruction::kNOP, AddressMode::kABX}},
	{0x3C, {Instruction::kNOP, AddressMode::kABX}},
	{0x5C, {Instruction::kNOP, AddressMode::kABX}},
	{0x7C, {Instruction::kNOP, AddressMode::kABX}},
	{0xDC, {Instruction::kNOP, AddressMode::kABX}},
	{0xFC, {Instruction::kNOP, AddressMode::kABX}},
	{0x87, {Instruction::kSAX, AddressMode::kZP}},
	{0x97, {Instruction::kSAX, AddressMode::kZPY}},
	{0x8F, {Instruction::kSAX, AddressMode::kABS}},
	{0x83, {Instruction::kSAX, AddressMode::kINX}},
	{0xEB, {Instruction::kUSBC, AddressMode::kIMM}},
	{0xC7, {Instruction::kDCP, AddressMode::kZP}},
	{0xD7, {Instruction::kDCP, AddressMode::kZPX}},
	{0xCF, {Instruction::kDCP, AddressMode::kABS}},
	{0xDF, {Instruction::kDCP, AddressMode::kABX}},
	{0xDB, {Instruction::kDCP, AddressMode::kABY}},
	{0xC3, {Instruction::kDCP, AddressMode::kINX}},
	{0xD3, {Instruction::kDCP, AddressMode::kINY}},
	{0xE7, {Instruction::kISC, AddressMode::kZP}},
	{0xF7, {Instruction::kISC, AddressMode::kZPX}},
	{0xEF, {Instruction::kISC, AddressMode::kABS}},
	{0xFF, {Instruction::kISC, AddressMode::kABX}},
	{0xFB, {Instruction::kISC, AddressMode::kABY}},
	{0xE3, {Instruction::kISC, AddressMode::kINX}},
	{0xF3, {Instruction::kISC, AddressMode::kINY}},
	{0x07, {Instruction::kSLO, AddressMode::kZP}},
	{0x17, {Instruction::kSLO, AddressMode::kZPX}},
	{0x0F, {Instruction::kSLO, AddressMode::kABS}},
	{0x1F, {Instruction::kSLO, AddressMode::kABX}},
	{0x1B, {Instruction::kSLO, AddressMode::kABY}},
	{0x03, {Instruction::kSLO, AddressMode::kINX}},
	{0x13, {Instruction::kSLO, AddressMode::kINY}},
	{0x27, {Instruction::kRLA, AddressMode::kZP}},
	{0x37, {Instruction::kRLA, AddressMode::kZPX}},
	{0x2F, {Instruction::kRLA, AddressMode::kABS}},
	{0x3F, {Instruction::kRLA, AddressMode::kABX}},
	{0x3B, {Instruction::kRLA, AddressMode::kABY}},
	{0x23, {Instruction::kRLA, AddressMode::kINX}},
	{0x33, {Instruction::kRLA, AddressMode::kINY}},
	{0x47, {Instruction::kSRE, AddressMode::kZP}},
	{0x57, {Instruction::kSRE, AddressMode::kZPX}},
	{0x4F, {Instruction::kSRE, AddressMode::kABS}},
	{0x5F, {Instruction::kSRE, AddressMode::kABX}},
	{0x5B, {Instruction::kSRE, AddressMode::kABY}},
	{0x43, {Instruction::kSRE, AddressMode::kINX}},
	{0x53, {Instruction::kSRE, AddressMode::kINY}},
	{0x67, {Instruction::kRRA, AddressMode::kZP}},
	{0x77, {Instruction::kRRA, AddressMode::kZPX}},
	{0x6F, {Instruction::kRRA, AddressMode::kABS}},
	{0x7F, {Instruction::kRRA, AddressMode::kABX}},
	{0x7B, {Instruction::kRRA, AddressMode::kABY}},
	{0x63, {Instruction::kRRA, AddressMode::kINX}},
	{0x73, {Instruction::kRRA, AddressMode::kINY}},
}};

} // namespace nes
